### ISSUE TITLE
Memtest fails to allocate a buffer. Tests 7.5GB only out of 12GB as well.

### ISSUE THREAD

**Issue by Ud4cznik** [GpuZelenograd/memtest_vulkan#46] opened 2024-08-07 17:16 UTC
seba@S-Z370-PC ~> memtest_vulkan
https://github.com/GpuZelenograd/memtest_vulkan v0.5.0 by GpuZelenograd
To finish testing use Ctrl+C

1: Bus=0x03:00 DevId=0x73DF   12GB AMD Radeon RX 6700 XT (RADV NAVI22)
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 10767560704 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 10348130304 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 9928699904 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 9509269504 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 9089839104 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
radv/amdgpu: Failed to allocate a buffer:
radv/amdgpu:    size      : 8670408704 bytes
radv/amdgpu:    alignment : 262144 bytes
radv/amdgpu:    domains   : 4
Standard 5-minute test of 1: Bus=0x03:00 DevId=0x73DF   12GB AMD Radeon RX 6700 XT (RADV NAVI22)
      1 iteration. Passed  0.0446 seconds  written:    3.8GB 281.2GB/sec        checked:    7.5GB 240.2GB/sec
     24 iteration. Passed  1.0237 seconds  written:   86.2GB 286.9GB/sec        checked:  172.5GB 238.6GB/sec
    137 iteration. Passed  5.0259 seconds  written:  423.8GB 288.6GB/sec        checked:  847.5GB 238.2GB/sec
^C
memtest_vulkan: no any errors, testing PASSed.
  press any key to continue...

**Comment by galkinvv** [comment] 2024-08-08 01:58
Thanks for reporting. This is known behavior and is mostly harmless compatibility issue with RADV driver.

Such behaviour was already discussed in detail in nearly duplicate issue https://github.com/GpuZelenograd/memtest_vulkan/issues/16

There are explaining why it is harmless and also highlighting some differences with AMDVLK driver variant.
Closing as duplicate, feel free to reopen if you think the issue is different

**Closed by galkinvv** 2024-08-08 01:58 UTC
